services:
    node-dind:
        build:
            context: .
            dockerfile: Dockerfile
        image: node-docker-local:latest
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            # add your compose stack file here
            # - /srv/stack1/compose.yaml:/app/stacks/stack1/compose.yaml:ro
        ports:
            - "3000"
        environment:
            - PORT=3000
